# Kitty terminal configuration
# https://sw.kovidgoyal.net/kitty/conf/

font_family JetBrainsMono Nerd Font Mono
font_size 15
confirm_os_window_close 0

# Navigate back/forward (Cmd+[ / Cmd+])
map super+[ send_key alt+left
map super+] send_key alt+right

# Window navigation (Cmd+h/j/k/l)
map super+h send_key alt+h
map super+j send_key alt+j
map super+k send_key alt+k
map super+l send_key alt+l


startup_session startup.conf

