return {
  -- Default
  { "rebelot/kanagawa.nvim", lazy = true },
  { "LazyVim/LazyVim", opts = { colorscheme = "kanagawa" } },

  -- Popular dark themes
  { "folke/tokyonight.nvim", lazy = true },
  { "catppuccin/nvim", name = "catppuccin", lazy = true },
  { "rose-pine/neovim", name = "rose-pine", lazy = true },
  { "EdenEast/nightfox.nvim", lazy = true },
  { "sainnhe/gruvbox-material", lazy = true },
  { "sainnhe/everforest", lazy = true },
  { "sainnhe/sonokai", lazy = true },
  { "sainnhe/edge", lazy = true },
  { "navarasu/onedark.nvim", lazy = true },
  { "Mofiqul/dracula.nvim", lazy = true },
  { "bluz71/vim-nightfly-colors", name = "nightfly", lazy = true },
  { "bluz71/vim-moonfly-colors", name = "moonfly", lazy = true },
  { "shaunsingh/nord.nvim", lazy = true },
  { "AlexvZyl/nordic.nvim", lazy = true },
  { "marko-cerovac/material.nvim", lazy = true },
  { "projekt0n/github-nvim-theme", lazy = true },
  { "nyoom-engineering/oxocarbon.nvim", lazy = true },
  { "Everblush/nvim", name = "everblush", lazy = true },
  { "scottmckendry/cyberdream.nvim", lazy = true },
  { "ribru17/bamboo.nvim", lazy = true },
  { "neanias/everforest-nvim", lazy = true },
  { "mhartington/oceanic-next", lazy = true },
  { "tiagovla/tokyodark.nvim", lazy = true },
  { "olimorris/onedarkpro.nvim", lazy = true },
  { "rmehri01/onenord.nvim", lazy = true },
  { "Shatur/neovim-ayu", lazy = true },
  { "ellisonleao/gruvbox.nvim", lazy = true },
  { "craftzdog/solarized-osaka.nvim", lazy = true },
  { "HoNamDuong/hybrid.nvim", lazy = true },
  { "0xstepit/flow.nvim", lazy = true },
  { "olivercederborg/poimandres.nvim", lazy = true },
  { "dgox16/oldworld.nvim", lazy = true },
  { "uloco/bluloco.nvim", dependencies = { "rktjmp/lush.nvim" }, lazy = true },
  { "maxmx03/fluoromachine.nvim", lazy = true },
  { "2nthony/vitesse.nvim", dependencies = { "MunifTanjim/nui.nvim" }, lazy = true },
}
